version: "3"
services:
  kafkapython:
    image: parthij15/kafka_python:0.0
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:80"
    networks:
      - webnet
networks:
  webnet: