version: "3"
services:
  producer:
    image: <<PRODUCER_IMAGE>>
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: any
    ports:
      - "8000:80"
    networks:
      - webnet
networks:
  webnet: